version: "2"
services:
  deepstream:
    image: deepstreamio/deepstream.io
    ports:
      - "6020:6020"

  quasar:
    build:
      context: .
      dockerfile: "./Dockerfile"
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"
    command: /bin/sh -c "yarn && quasar dev"
